# Generated by Django 4.0.10 on 2023-10-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('child_category', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name'], name='report_app__name_90bb8a_idx'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report_app.task'),
        ),
        migrations.AddField(
            model_name='activityimages',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_app.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_units', to='report_app.unit'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_sub_task', to='report_app.subtask'),
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='report_app.task'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['id', 'slug'], name='report_app__id_da36f9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['name'], name='report_app__name_id_aede87_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-created'], name='report_app__created_0cf9ce_idx'),
        ),
    ]
