# Generated by Django 4.0.10 on 2023-10-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
        migrations.AddField(
            model_name='activityimages',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
