# Generated by Django 4.0.10 on 2023-10-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_remove_activity_price_activityimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='activities_units', to='report_app.unit'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sub_task',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_sub_task', to='report_app.subtask'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='report_app.task'),
        ),
    ]
