# Generated by Django 4.0.10 on 2023-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_alter_activity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
