# Generated by Django 4.0.10 on 2023-10-15 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_alter_activity_description_alter_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
