# Generated by Django 4.0.10 on 2023-10-22 12:06

from django.db import migrations, models
import report_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_alter_activity_created'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='report_app__name_id_aede87_idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name=report_app.models.Unit),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sub_task',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=report_app.models.SubTask),
        ),
        migrations.AlterField(
            model_name='activity',
            name='task',
            field=models.CharField(max_length=100, verbose_name=report_app.models.Task),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['name'], name='report_app__name_337c41_idx'),
        ),
    ]
