# Generated by Django 4.0.10 on 2023-10-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0005_remove_activity_report_app__name_id_aede87_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
