# Generated by Django 4.0.10 on 2023-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_alter_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
