# Generated by Django 4.0.10 on 2023-12-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_alter_activityimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
