# Generated by Django 4.0.10 on 2023-12-09 06:16

from django.db import migrations, models
import report_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0007_alter_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[report_app.validators.validate_file_size]),
        ),
    ]
