# Generated by Django 4.0.10 on 2023-10-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0010_alter_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
