# Generated by Django 4.0.10 on 2023-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0011_alter_activity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
