# Generated by Django 4.0.10 on 2023-10-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0012_alter_activity_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='report_app__id_da36f9_idx',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['id'], name='report_app__id_7bf2ef_idx'),
        ),
    ]
