# Generated by Django 4.0.10 on 2023-10-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0013_remove_activity_report_app__id_da36f9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
