# Generated by Django 4.0.10 on 2023-10-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0014_alter_activity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='shamsi',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
