# Generated by Django 4.0.10 on 2023-10-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0015_activity_shamsi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created']},
        ),
    ]
