# Generated by Django 4.0.10 on 2023-11-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0017_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='str_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
