# Generated by Django 4.0.10 on 2023-11-11 06:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0018_activity_str_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='colleague',
            field=models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
